services:
  - type: web
    name: aidatascience
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
