"""
Export Service — Generates fully reproducible Jupyter Notebooks (.ipynb)
and standalone Python scripts (.py) from experiments and cleaning pipelines.
"""
import json
import logging
from typing import Dict, Any, Optional
from sqlalchemy.orm import Session

from app.db.models import Experiment, Dataset, PipelineStep, MLModel

logger = logging.getLogger(__name__)


class ExportService:
    @staticmethod
    def generate_script(experiment_id: str, db: Session) -> str:
        """Generate a complete, executable Python script reproducing the experiment."""
        exp = db.query(Experiment).filter(Experiment.id == experiment_id).first()
        if not exp:
            raise ValueError(f"Experiment {experiment_id} not found")

        dataset = db.query(Dataset).filter(Dataset.id == exp.dataset_id).first()
        pipeline_steps = db.query(PipelineStep).filter(
            PipelineStep.dataset_id == exp.dataset_id,
            PipelineStep.is_active == True
        ).order_by(PipelineStep.step_order.asc()).all()

        target = exp.target_column
        task_type = exp.task_type.value if hasattr(exp.task_type, "value") else str(exp.task_type)
        algorithm = exp.algorithm
        hyperparams = json.loads(exp.hyperparameters) if exp.hyperparameters else {}

        # Build cleaning steps code
        cleaning_code_lines = []
        for step in pipeline_steps:
            params = json.loads(step.params) if step.params else {}
            op = step.operation
            if op == "drop_duplicates":
                cleaning_code_lines.append("df = df.drop_duplicates()")
            elif op == "drop_column":
                col = params.get("column")
                if col:
                    cleaning_code_lines.append(f"if '{col}' in df.columns: df = df.drop(columns=['{col}'])")
            elif op == "impute_missing":
                col = params.get("column")
                strategy = params.get("strategy", "median")
                if col:
                    if strategy == "median":
                        cleaning_code_lines.append(f"df['{col}'] = df['{col}'].fillna(df['{col}'].median())")
                    elif strategy == "mean":
                        cleaning_code_lines.append(f"df['{col}'] = df['{col}'].fillna(df['{col}'].mean())")
                    elif strategy == "mode":
                        cleaning_code_lines.append(f"df['{col}'] = df['{col}'].fillna(df['{col}'].mode()[0])")
                else:
                    cleaning_code_lines.append(
                        "# Auto-impute: numeric with median, categoricals with mode\n"
                        "for c in df.select_dtypes(include=['number']).columns:\n"
                        "    df[c] = df[c].fillna(df[c].median())\n"
                        "for c in df.select_dtypes(include=['object', 'category']).columns:\n"
                        "    if not df[c].mode().empty:\n"
                        "        df[c] = df[c].fillna(df[c].mode()[0])"
                    )
            elif op == "clip_outliers":
                col = params.get("column")
                factor = params.get("iqr_factor", 1.5)
                if col:
                    cleaning_code_lines.append(
                        f"q1 = df['{col}'].quantile(0.25)\n"
                        f"q3 = df['{col}'].quantile(0.75)\n"
                        f"iqr = q3 - q1\n"
                        f"df['{col}'] = df['{col}'].clip(q1 - {factor} * iqr, q3 + {factor} * iqr)"
                    )

        cleaning_block = "\n".join(cleaning_code_lines) if cleaning_code_lines else "# No additional cleaning steps"

        # Model imports & definition
        is_classification = "classification" in task_type
        if algorithm == "random_forest":
            model_import = "from sklearn.ensemble import RandomForestClassifier" if is_classification else "from sklearn.ensemble import RandomForestRegressor"
            model_class = "RandomForestClassifier" if is_classification else "RandomForestRegressor"
        elif algorithm == "xgboost":
            model_import = "from xgboost import XGBClassifier" if is_classification else "from xgboost import XGBRegressor"
            model_class = "XGBClassifier" if is_classification else "XGBRegressor"
        else:
            model_import = "from sklearn.linear_model import LogisticRegression" if is_classification else "from sklearn.linear_model import LinearRegression"
            model_class = "LogisticRegression" if is_classification else "LinearRegression"

        hyperparams_str = ", ".join([f"{k}={repr(v)}" for k, v in hyperparams.items()])

        filename = dataset.original_filename if dataset else "dataset.csv"

        script = f'''"""
Auto-Generated Reproducible ML Pipeline
Generated by AI Data Scientist Platform
Experiment: {exp.name}
Model: {algorithm} | Task: {task_type}
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
{model_import}
from sklearn.metrics import { 'classification_report, accuracy_score, f1_score' if is_classification else 'mean_squared_error, r2_score, mean_absolute_error' }

# 1. Load Dataset
print("Loading dataset...")
df = pd.read_csv("{filename}")
print(f"Loaded dataset: {{df.shape[0]}} rows, {{df.shape[1]}} columns")

# 2. Apply Non-Destructive Cleaning Pipeline
print("Applying cleaning pipeline...")
{cleaning_block}

# 3. Define Features and Target
target_column = "{target}"
X = df.drop(columns=[target_column])
y = df[target_column]

# Separate numeric and categorical features
numerical_cols = X.select_dtypes(include=[np.number]).columns.tolist()
categorical_cols = X.select_dtypes(include=['object', 'category', 'bool']).columns.tolist()
print(f"Features: {{len(numerical_cols)}} numerical, {{len(categorical_cols)}} categorical")

# 4. Build Sklearn Preprocessing Pipelines
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ]
)

# 5. Define Model
model = {model_class}({hyperparams_str})

full_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier' if {is_classification} else 'regressor', model)
])

# 6. Train / Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size={exp.train_test_split}, random_seed={exp.random_seed} if hasattr(exp, 'random_seed') else 42
)

# 7. Fit Pipeline
print("Fitting model pipeline...")
full_pipeline.fit(X_train, y_train)

# 8. Evaluate on Test Set
y_pred = full_pipeline.predict(X_test)
print("\\n--- Evaluation Results ---")
'''
        if is_classification:
            script += '''
print("Accuracy:", round(accuracy_score(y_test, y_pred), 4))
print("F1-Score:", round(f1_score(y_test, y_pred, average='weighted'), 4))
print("\\nClassification Report:\\n", classification_report(y_test, y_pred))
'''
        else:
            script += '''
print("R² Score:", round(r2_score(y_test, y_pred), 4))
print("MAE:", round(mean_absolute_error(y_test, y_pred), 4))
print("RMSE:", round(np.sqrt(mean_squared_error(y_test, y_pred)), 4))
'''
        return script

    @classmethod
    def generate_notebook(cls, experiment_id: str, db: Session) -> str:
        """Generate a Jupyter Notebook (.ipynb format) with separate explanatory cells."""
        script = cls.generate_script(experiment_id, db)
        
        # Split script sections into notebook cells
        sections = script.split("# ")
        cells = []

        # Intro markdown cell
        cells.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🤖 Auto-Generated Machine Learning Pipeline\n",
                "This notebook reproduces the complete data cleaning, feature transformation, and model training workflow.\n"
            ]
        })

        for sec in sections:
            if not sec.strip():
                continue
            lines = sec.split("\n")
            header = lines[0].strip()
            code_lines = [f"{line}\n" for line in lines[1:]]

            # Add markdown step header
            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [f"### 📌 {header}\n"]
            })

            # Add code cell
            if any(l.strip() for l in code_lines):
                cells.append({
                    "cell_type": "code",
                    "execution_count": None,
                    "metadata": {},
                    "outputs": [],
                    "source": code_lines
                })

        notebook = {
            "cells": cells,
            "metadata": {
                "language_info": {
                    "name": "python",
                    "version": "3.10"
                }
            },
            "nbformat": 4,
            "nbformat_minor": 4
        }
        return json.dumps(notebook, indent=2)
